/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/kdojDKiIs7q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent, SheetTitle } from "@/components/ui/sheet"

export function PublicNavbar({
    signIn = true,
    signUp = true,
    home = true,
    signInVariant = "link",
    signUpVariant = "link"
  }:{
    signIn?: boolean,
    signUp?: boolean
    home?: boolean
    signInVariant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link'
    signUpVariant?: 'default' | 'destructive' | 'outline' | 'secondary' | 'ghost' | 'link'
  }) {
  return (
    <header className="flex h-16 w-full items-center justify-between px-4 md:px-6">
      <Link href="/" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <nav className="hidden items-center gap-6 text-sm font-medium md:flex">
        {home && (
          <Link href="/" className="hover:underline hover:underline-offset-4" prefetch={false}>
            Home
          </Link>
        )}
        <div className="flex items-center gap-2">
          {signIn && (
            <Link href="/sign-in">
              <Button variant="link" className="!text-black">Login</Button>
            </Link>
          )}
          {signUp && (
            <Link href="/sign-up">
              <Button variant="link" className="!text-black">Sign Up</Button>
            </Link>
          )}
        </div>
      </nav>
      <Sheet>
        <SheetTrigger asChild>
          <Button variant="default" size="icon" className="md:hidden">
            <MenuIcon className="h-6 w-6" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left" className="!bg-white">
          <SheetTitle></SheetTitle>
          <div className="grid gap-4 p-4">
            <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
              <MountainIcon className="h-6 w-6" />
              <span className="sr-only">Acme Inc</span>
            </Link>
            <nav className="grid gap-2">
              {home && (
                <Link
                  href="/"
                  className="flex items-center gap-2 py-2 text-sm font-medium hover:underline hover:underline-offset-4"
                  prefetch={false}
                >
                  Home
                </Link>
              )}
              <div className="flex flex-col items-start gap-2">
              {signIn && (
                <Link href="/sign-in">
                  <Button variant={signInVariant} className="!text-black">Login</Button>
                </Link>
              )}
              {signUp && (
                <Link href="/sign-up">
                  <Button variant={signUpVariant} className="!text-black">Sign Up</Button>
                </Link>
              )}
                <Link href="https://github.com/tylerbert31" target="_blank">
                  <Button className="!text-black" variant="link">Github</Button>
                </Link>
                <Link href="https://www.linkedin.com/in/tyler-bert-baring-156464270/?original_referer=" target="_blank">
                  <Button className="!text-black" variant="link">LinkedIn</Button>
                </Link>
              </div>
            </nav>
          </div>
        </SheetContent>
      </Sheet>
    </header>
  )
}

function MenuIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}
